#!/usr/bin/env node
/* Bleed Control — full test suite.   node tests/run_all.js   (exit code 0 = all passed)
   Sections: syntax balance lesson stations scenarios human wrong slow drills record fuzz      (or: quick) */
global.window=global.window||{};
const path=require('path'),fs=require('fs'),vm=require('vm');
const ALL=['syntax','balance','lesson','stations','scenarios','human','wrong','slow','drills','record','drill','teach','vein','bike','auger','hunt','fwk','smooth','fuzz'];
let want=process.argv.slice(2);if(!want.length)want=ALL;if(want.includes('quick'))want=['syntax','balance','lesson','drills','record','fuzz'];
let failed=0,n=0;const T0=Date.now();
function report(sec,name,ok,detail=''){n++;if(!ok)failed++;console.log(`${ok?'PASS':'FAIL'}  ${sec.padEnd(9)} ${name}${detail?'  — '+detail:''}`);}
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');const {boot}=require('./bc_mock.js');const bot=require('./bc_bot.js');
const SC=['kitchen','garage','glass','crash','vein','bike','auger','hunt','fwk'],TIERS=['Guided','Recall','Chaos'];
if(want.includes('syntax')){try{new vm.Script(html.split('<script>')[1].split('</script>')[0]);report('syntax','index.html script compiles',true);}catch(e){report('syntax','index.html script compiles',false,e.message);}
  {const ver=(html.match(/APP_VERSION='([^']+)'/)||[])[1],sw=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8'),cache=(sw.match(/CACHE = '([^']+)'/)||[])[1];
   report('syntax','service-worker cache matches app version',cache===`bleed-control-v${ver}`,`app ${ver}, cache ${cache}`);
  {const {api}=boot();api.setSetting('text','large');report('syntax','settings sheet present and wired to the shared key',/id="setov"/.test(html)&&/id="h-set"/.test(html)&&api.settings().text==='large');}
  {// Milestone 3: the shared core is loaded before the app, listed in the offline cache, and its header hash matches its body (edit without re-hashing = fail)
   const cp=path.join(__dirname,'..','preconnect-core.js');const ct=fs.existsSync(cp)?fs.readFileSync(cp,'utf8'):'';const first=ct.split('\n')[0]||'';const body=ct.slice(first.length+1);
   const want=(first.match(/sha256:([0-9a-f]{64})/)||[])[1];const got=require('crypto').createHash('sha256').update(body,'utf8').digest('hex');const sw4=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8');
   const tagOK=html.indexOf('<script src="preconnect-core.js"></script>')>-1&&html.indexOf('<script src="preconnect-core.js"></script>')<html.indexOf('\n<script>\n');
   report('syntax','shared core loaded first, cached offline, header hash matches body',!!ct&&want===got&&sw4.includes("'preconnect-core.js'")&&tagOK,want===got?'hash ok':`hash expected ${got.slice(0,12)}`);}
  {// Milestone 3: due-again spacing and the debrief body are pure functions; prove them here
   const {boot}=require('./bc_mock.js');const {api}=boot();const d=n=>new Date(Date.now()-n*864e5).toISOString();
   const never=api.pcSpacing([]).status==='never',one=api.pcSpacing([{d:d(0),score:90}]),two=api.pcSpacing([{d:d(5),score:90},{d:d(4),score:90}]),miss=api.pcSpacing([{d:d(5),score:90},{d:d(1),score:40}]),due=api.pcSpacing([{d:d(10),score:95}]);
   report('syntax','spacing: 1, 3, 7, 14, 30 days after each clear at 70+; a miss resets; overdue reads as due',never&&one.level===1&&one.dueIn===1&&one.status==='ok'&&two.level===2&&two.status==='due'&&miss.status==='missed'&&due.status==='due'&&due.level===1,`one ${one.status}/${one.dueIn}d, two ${two.status}, miss ${miss.status}, due ${due.status}`);
   const bp=api.pcBestPrev([{d:d(3),score:80},{d:d(1),score:60}]);const h=api.pcDebriefBody({score:90,compare:bp,metrics:[['Rate','110 / min']],feedback:['Late breath'],lessons:[{k:'x',name:'Breaths'}],steps:[{name:'Check pulse',ok:true,at:'0:05'},{name:'Shock',ok:false,missed:true}]});
   report('syntax','debrief body: compare line, metrics table, what cost points, lessons, steps table',bp.best===80&&bp.prev===60&&/Best 80 · last time 60 · new best/.test(h)&&/pc-metrics/.test(h)&&/What cost points/.test(h)&&/data-k="x"/.test(h)&&/pc-steps/.test(h)&&/✗/.test(h));}

  {// Milestone 1: fonts are served from this site; nothing loads from Google (offline fidelity + privacy). Every font file exists and is in the offline cache list.
   const sw3=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8');const urls=[...html.matchAll(/url\((fonts\/[^)]+)\)/g)].map(m=>m[1]);
   const ok=!/fonts\.googleapis|gstatic\.com/.test(html)&&urls.length>=5&&urls.every(u=>fs.existsSync(path.join(__dirname,'..',u))&&sw3.includes(`'${u}'`));
   report('syntax','fonts served from this site, cached offline, no request to Google',ok,`${urls.length} font files`);}
  {// Milestone 1: the screen stays awake while an activity runs and is released after (stubbed wake lock; the real one is async)
   const {api}=boot();let req=0,rel=0;const lock={addEventListener(){},release(){rel++;return Promise.resolve();}};navigator.wakeLock={request(){req++;return {then(f){f(lock);return {catch(){}};}};}};
   try{api.lessonStart();}catch(e){report('syntax','screen stays awake during an activity, released after',false,e.message);}
   const a=req>=1;api.showHome();report('syntax','screen stays awake during an activity, released after',a&&rel>=1&&rel===req,`requests ${req}, releases ${rel}`);delete navigator.wakeLock;}

  report('syntax','offline helper only clears its own old caches',/k\.startsWith\('bleed-control-v'\)/.test(fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8')));
  {const sw2=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8');report('syntax','offline helper never caches anonymous statistics',/goatcounter\\\.com\$\|\(\^\|\\\.\)zgo\\\.at/.test(sw2)||sw2.includes('goatcounter')&&sw2.includes('zgo'));}
  {// Milestone B (final sweep, M1): the page and the shared core are both network-first with a short wait, bad answers are never saved, installs skip the HTTP cache, and index.html is stored once
   const sw5=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8');const coreNF=sw5.includes("netFirst(req, 'preconnect-core.js')")&&/fellBack = Date\.now\(\)/.test(sw5),navNF=/req\.mode === 'navigate'\)\s*\{\s*e\.respondWith\(netFirst/.test(sw5),wait=/const NET_WAIT = (\d+)/.test(sw5)&&+sw5.match(/const NET_WAIT = (\d+)/)[1]<=4000&&/Promise\.race\(\[net, wait\]\)/.test(sw5),okOnly=/if \(r\.ok\) \{ const copy = r\.clone\(\); caches\.open\(CACHE\)\.then\(c => c\.put\(key, copy\)\)/.test(sw5),reload=/cache: 'reload'/.test(sw5),once=!/CORE = \['\.\/'/.test(sw5)&&/'index\.html'/.test(sw5);
   report('syntax','offline helper: page and shared core network-first with a short wait, bad answers never saved, fresh installs skip the HTTP cache, index stored once',coreNF&&navNF&&wait&&okOnly&&reload&&once,`core ${coreNF} nav ${navNF} wait ${wait} ok ${okOnly} reload ${reload} once ${once}`);}
   const man=JSON.parse(fs.readFileSync(path.join(__dirname,'..','manifest.json'),'utf8'));report('syntax','install manifest, icons, and offline helper wired up',/rel="manifest"/.test(html)&&/serviceWorker\.register\('sw\.js'\)/.test(html)&&man.icons.length>=2&&fs.existsSync(path.join(__dirname,'..','icon-512.png')));}
  report('syntax','trademark notice and "not affiliated" statement present',/registered trademark of the U\.S\. Department of Defense/.test(html)&&/not affiliated/.test(html));
  report('syntax','app name does not use the trademarked phrase',!/<title>[^<]*Stop the Bleed/i.test(html)&&!/class="brand">[^<]*STOP THE BLEED/i.test(html));}
if(want.includes('balance')){const {api}=boot();let lo=0,sh=0,t=0,miss=0;const chk=o=>{const L=o.map(x=>x[0].length),g=o.findIndex(x=>x[1]==='good');if(g<0){miss++;return;}t++;if(L[g]===Math.max(...L))lo++;else if(L[g]===Math.min(...L))sh++;};
  api.LESSON.forEach(s=>chk(s.o));Object.values(api.DEC).forEach(d=>chk(d.o));
  report('balance','right answer not usually the longest',lo/t<=.45,`${lo} of ${t}`);report('balance','right answer not usually the shortest',sh/t<=.45,`${sh} of ${t}`);report('balance','every question has exactly one right answer',miss===0);}
if(want.includes('lesson')){for(const mode of ['right','wrong']){const {api,els}=boot();api.lessonStart();let g=0;
  while(api.LS()&&g++<60){const L=api.LS(),s=api.LESSON[L.i];if(mode==='wrong'&&L.first[L.i]===undefined){api.lessonAct({l:'ans',k:String(s.o.findIndex(x=>x[1]!=='good'))});}api.lessonAct({l:'ans',k:String(s.o.findIndex(x=>x[1]==='good'))});api.lessonAct({l:'next'});}
  report('lesson',`all 12 slides; first-try ${mode} scores ${mode==='right'?100:0}`,String(els['done-s'].textContent)===(mode==='right'?'100':'0'),'score '+els['done-s'].textContent);}
  {const {api}=boot();api.lessonStart();api.lessonAct({l:'next'});report('lesson','cannot skip a slide without answering its check',api.LS().i===0);}}
if(want.includes('stations')){for(const [id,f] of [['tq-arm',{near:false}],['tq-arm',{near:true}],['tq-leg',{need2:false}],['tq-leg',{need2:true}],['pack',{site:'groin'}],['pack',{site:'armpit'}],['press',{}]]){const r=bot.playStation(id,{force:{[id]:f}});report('stations',`${id} ${JSON.stringify(f)} clean run scores 100`,r.ok&&r.score===100,'score '+r.score);}
  let r=bot.playStation('tq-arm',{wrongZone:true,force:{'tq-arm':{near:true}}});report('stations','tourniquet tapped onto the elbow is caught',r.ok&&r.score<100,'score '+r.score);
  r=bot.playStation('tq-arm',{noTime:true});report('stations','skipping the time is caught',r.ok&&r.score<100,'score '+r.score);
  {// 0.15.0 (Max, October 8, 2026): a tourniquet on yourself, one-handed; general technique, marked to confirm
   const c=bot.playStation('self',{}),h=bot.playStation('self',{human:true});report('stations','self, one-handed: a clean run scores 100 (instantly and at human pace)',c.ok&&c.score===100&&h.ok&&h.score===100,`${c.score} / ${h.score}`);
   const m=[['call 911 before the tourniquet',{selfFirst:'call1'}],['walk to find help',{selfFirst:'walk'}],['grip with the hurt hand',{grip:true}],['let go of the rod',{letgo:true}],['wait for someone instead of calling',{wait:true}]].map(([n,o])=>{const r=bot.playStation('self',o);return [n,r.ok&&r.score<=90,r.score];});
   report('stations','self, one-handed: each mistake is allowed, costs points, and the run still finishes',m.every(x=>x[1]),m.map(x=>x[0]+' '+x[2]).join(', '));
   const {api,els}=boot();api.practice('self');const first=els['st-prompt'].textContent,btn=els['st-btns'].innerHTML;api.$('st-btns').onclick({target:{closest:()=>({dataset:{s:'call1'}})}});const called=api.ST().called&&api.ST().phase==='place';
   report('stations','self: the "to confirm" note shows, calling first really happens (the last step becomes "tell the dispatcher the time"), and the station is on the home list and in the record',/to confirm with your instructor/.test(first)&&/data-s="sit"/.test(btn)&&called&&/data-st="self"/.test(html)&&api.STN.self==='Tourniquet on yourself, one-handed');}
  {// 0.16.0 (Max, October 8, 2026): talk a bystander through a tourniquet with words only
   const c=bot.playStation('coach',{}),h=bot.playStation('coach',{human:true});report('stations','coach: seven clear instructions in order score 100 (instantly and at human pace)',c.ok&&c.score===100&&h.ok&&h.score===100,`${c.score} / ${h.score}`);
   const v=bot.playStation('coach',{coach:{1:'vague'}}),o=bot.playStation('coach',{coach:{0:'out'}}),lk=bot.playStation('coach',{coach:{4:'vague'}}),nv=bot.playStation('coach',{coach:{6:'out'}});
   report('stations','coach: a vague instruction or one out of order costs a mistake and the run still finishes; "let go" before the lock really unwinds the rod',[v,o,lk,nv].every(r=>r.ok&&r.score<=90),`vague ${v.score}, order ${o.score}, let go ${lk.score}, loosen ${nv.score}`);
   const {api,els}=boot();api.practice('coach');const say=k=>api.$('st-btns').onclick({target:{closest:()=>({dataset:{s:'say-'+k}})}});say('vague');const lit=/can't find the cut/.test(els['st-fb'].innerHTML)&&api.ST().ci===0;
   say('good');say('vague');const onCut=/right over the cut/.test(els['st-fb'].innerHTML)&&api.ST().ci===1;say('good');say('good');say('good');const ci4=api.ST().ci;say('vague');const back=api.ST().ci===3&&/unwinds/.test(els['st-fb'].innerHTML);
   report('stations','coach: the bystander does exactly what you say (he can\'t find the cut, puts it on the wound, lets go and it unwinds)',lit&&onCut&&ci4===4&&back);
   let lo=0,sh=0;for(let i=0;i<api.COACH.length;i++){const L=api.coachOpts(i).map(x=>x[1].length);if(L[0]===Math.max(...L))lo++;else if(L[0]===Math.min(...L))sh++;}
   report('stations','coach: the clear instruction is not usually the longest or the shortest (both under 45%)',lo/api.COACH.length<=.45&&sh/api.COACH.length<=.45,`longest ${lo}, shortest ${sh} of ${api.COACH.length}`);}}
if(want.includes('scenarios'))for(const id of SC){let ok=0;for(const t of [0,1,2]){const r=bot.playScenario(id,t);if(r.ok&&!r.died&&r.score===100)ok++;}report('scenarios',`${id}: all tiers survive with a perfect score`,ok===3,`${ok}/3`);}
if(want.includes('human')){for(const id of SC){let ok=0;const sc=[];for(const t of [0,1,2]){const r=bot.playScenario(id,t,'good',{human:true});if(r.ok&&!r.died)ok++;sc.push(r.score);}report('human',`${id}: survives at human pace on every tier`,ok===3,'scores '+sc.join('/'));}
  for(const [id,f] of [['kitchen',{kit:true,near:true}],['kitchen',{kit:false}],['garage',{need2:true}],['glass',{site:'armpit'}],['glass',{site:'groin'}]]){const r=bot.playScenario(id,0,'good',{human:true,force:{[id]:f}});report('human',`${id} ${JSON.stringify(f)} at human pace`,r.ok&&!r.died&&r.score===100,'score '+r.score);}}
if(want.includes('wrong'))for(const id of SC)for(const ch of ['partial','bad']){const r=bot.playScenario(id,0,ch,{force:{kitchen:{kit:false}}});report('wrong',`${id}: completable after ${ch} decisions, score drops`,r.ok&&r.score<100,'score '+r.score);}
if(want.includes('slow')){const s45=SC.map(id=>bot.playScenario(id,0,'good',{human:true,slow:45,force:{kitchen:{kit:true}}}).score),s75=SC.map(id=>bot.playScenario(id,0,'good',{human:true,slow:75,force:{kitchen:{kit:true}}}).score);
  report('slow','scores fall as response slows (45 s, then 75 s)',s45.every((x,i)=>x>s75[i]&&x<=100)&&s75.every(x=>x<90),`45 s: ${s45.join('/')} · 75 s: ${s75.join('/')}`);
  const u=bot.playScenario('garage',0,'good',{human:true,noPress:true,slow:600});report('slow','no bleeding control at all is fatal',u.died,`lost ${u.lost} mL`);}
if(want.includes('drills')){for(const k of ['threat','method','place','kit']){const sc={};for(const mode of ['right','wrong']){const {api,els}=boot();api.drillMenu();api.drillAct({d:'go',k});let g=0;
  while(api.DR()&&api.DR().i<api.DR().qs.length&&g++<20){const q=api.DR().qs[api.DR().i];const i=mode==='right'?q.ord.indexOf(q.a):q.ord.findIndex(o=>o!==q.a);api.drillAct({d:'ans',i:String(i)});api.drillAct({d:'next'});}
  sc[mode]=(els['dr-body'].innerHTML.match(/class="big">(\d+)/)||[])[1];}report('drills',`${k}: all right 100, all wrong 0`,sc.right==='100'&&sc.wrong==='0',`${sc.right}/${sc.wrong}`);}
  let bad=0;const {api}=boot();for(const k of ['threat','method','place','kit'])for(let i=0;i<100;i++)for(const q of api.DRILLS[k].items()){if(!q.opts.includes(q.a)||new Set(q.opts).size!==q.opts.length)bad++;}report('drills','400 generated drill sets well-formed (answer present, no duplicates)',bad===0,bad?bad+' bad':'');
  {// Kit check: an independent reading of what a bleeding control kit holds (the test's own list, not the app's tables)
   const BELONGS=/tourniquet|gauze|gloves|marker|shears|blanket|pressure bandage/i,NOT=/peroxide|ointment|cold pack|adhesive|belt|smelling|alcohol/i;let wrong=0,lo=0,sh=0,t=0,n8=0;
   for(let i=0;i<200;i++){const qs=api.DRILLS.kit.items();if(qs.length===8&&new Set(qs.map(q=>q.q)).size===8)n8++;
    for(const q of qs){const L=q.opts.map(o=>o.length),g=q.opts.indexOf(q.a);t++;if(L[g]===Math.max(...L))lo++;else if(L[g]===Math.min(...L))sh++;
     if(/^Which of these belongs/.test(q.q)&&!(BELONGS.test(q.a)&&q.opts.filter(o=>o!==q.a).every(o=>NOT.test(o))))wrong++;
     if(/does NOT belong/.test(q.q)&&!(NOT.test(q.a)&&q.opts.filter(o=>o!==q.a).every(o=>BELONGS.test(o))))wrong++;
     if(/^Kit check\. Inside: (.*)\. What is missing/.test(q.q)){const inside=q.q.match(/Inside: (.*)\. What is missing/)[1].toLowerCase();const key=o=>o.replace(/^(A|An|Two pairs of) /,'').toLowerCase();
      if(inside.includes(key(q.a))||!q.opts.filter(o=>o!==q.a).every(o=>inside.includes(key(o))))wrong++;}}}
   report('drills','kit check: eight distinct questions a run; "belongs", "does not belong" and "what is missing" keys agree with an independent reading of the kit',wrong===0&&n8===200,`${wrong} disagree, ${n8}/200 runs of eight`);
   report('drills','kit check: the right answer is not usually the longest or the shortest (both under 45%)',lo/t<=.45&&sh/t<=.45,`longest ${Math.round(lo/t*100)}%, shortest ${Math.round(sh/t*100)}%`);
   const fx=api.DRILLS.kit.items().map(q=>q.q+' '+q.opts.join(' ')).join(' ');report('drills','kit check teaches the trainer tourniquet, dates, restocking and where kits are found, and claims no law',api.KIT_FIXED.some(q=>/TRAINER/.test(q.q))&&api.KIT_FIXED.some(q=>/date/.test(q.q))&&api.KIT_FIXED.some(q=>/restock/i.test(q.q))&&api.KIT_FIXED.some(q=>/AED/.test(q.a))&&!/\blaw\b|required by|statute/i.test(JSON.stringify(api.KIT_FIXED)+fx));}
  {// Max, October 8, 2026: the neck is junctional (pack and press), never anything around the neck, never across the windpipe; hemostatic gauze held at least 3 minutes, then until help takes over
   const les=JSON.stringify(api.LESSON),meth=api.DRILLS.method,neck=meth.items().find(q=>/neck/.test(q.q));
   report('drills','the lesson, the packing station, the reference and "Which technique?" agree: neck = pack and press, never wrapped, not across the windpipe; hemostatic gauze at least 3 minutes',/never across the windpipe/.test(les)&&/never wrap anything around the neck/.test(les)&&/at least 3 minutes/.test(les)&&neck&&neck.a==='Pack it, then press'&&/never wrap anything around the neck/.test(meth.why)&&/never across the windpipe/.test(html.match(/<h2>Pocket reference[\s\S]*?`\)/)[0])&&/at least 3 minutes, then until help takes over \(shortened here\)/.test(html));}}
if(want.includes('record')){const {api,els}=boot();bot.stationStep;api.lessonStart();while(api.LS()){const s=api.LESSON[api.LS().i];api.lessonAct({l:'ans',k:String(s.o.findIndex(x=>x[1]==='good'))});api.lessonAct({l:'next'});}
  const p=api.load();report('record','lesson result saved to practice record',p.runs.some(r=>r.kind==='lesson'&&r.score===100));
  els['h-prog'].onclick();els['p-name'].value='Test Student';els['p-dept'].value='Monitor Twp';els['p-csv'].onclick();const csv=global.__csv||'';
  report('record','CSV export has header and rows',/"Name","Organization","Type","Activity"/.test(csv)&&/Test Student/.test(csv),csv.split('\n').length-1+' rows');}
if(want.includes('drill')){const start=new Date().toISOString();const {api,els}=boot({'preconnect-drill':JSON.stringify({on:true,inst:'Max',roster:['Jo'],who:'Jo',start})});let std=true;
  for(let k=0;k<10;k++){api.scStart('kitchen');const v=api.V();if(!(v.kit===true&&v.near===false))std=false;api.scStart('glass');if(api.V().site!=='groin')std=false;api.scStart('garage');if(api.V().need2!==false)std=false;api.scStart('vein');if(JSON.stringify(api.V())!==JSON.stringify(api.STD_V.vein))std=false;api.scStart('bike');if(JSON.stringify(api.V())!==JSON.stringify(api.STD_V.bike))std=false;api.scStart('auger');if(JSON.stringify(api.V())!==JSON.stringify(api.STD_V.auger))std=false;api.scStart('hunt');if(JSON.stringify(api.V())!==JSON.stringify(api.STD_V.hunt))std=false;api.scStart('fwk');if(JSON.stringify(api.V())!==JSON.stringify(api.STD_V.fwk))std=false;}
  api.showHome();api.lessonStart();while(api.LS()){const s=api.LESSON[api.LS().i];api.lessonAct({l:'ans',k:String(s.o.findIndex(x=>x[1]==='good'))});api.lessonAct({l:'next'});}const runs=api.load().runs;const r=runs[runs.length-1];
  report('drill','Drill Night: the same patient in every scenario, bar shows who is up, the saved lesson names them with the instructor and the night',std&&/Up: Jo/.test(els['pc-drill'].innerHTML)&&(r.who||[])[0]==='Jo'&&r.inst==='Max'&&r.night===start,`who ${r.who}, inst ${r.inst}`);}

if(want.includes('drill')){const fakeAudio=()=>{const log=[];const AC=function(){this.currentTime=0;this.state='running';this.destination={};this.resume=()=>{};this.createOscillator=()=>({type:'sine',frequency:{value:0},connect(){},start(t){log.push({f:this.frequency.value,t});},stop(){}});this.createGain=()=>({gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){}});};const buzz=[];const F={log,buzz,fs:()=>log.map(x=>x.f),arm(){global.window=global.window||{};global.window.AudioContext=AC;navigator.vibrate=p=>{buzz.push(JSON.stringify(p));return true;};}};F.arm();return F;};const F=fakeAudio();const {api}=boot();F.arm();api.setSetting('sound','on');api.scStart('kitchen');F.log.length=0;F.buzz.length=0;api.ding(5,'test');const bad=F.fs().includes(220)&&F.buzz.includes('[30,40,30]');F.log.length=0;api.showDone('t',90,'',()=>{});const done=F.fs().join().includes('523,659,784')&&F.buzz.includes('[20,60,20,60,40]');delete global.window.AudioContext;delete navigator.vibrate;
  report('drill','sound and haptics: a penalty plays the bad tone and buzzes, the result screen chimes',bad&&done,`bad ${bad}, done ${done}`);}

if(want.includes('drill')){global.__loc={search:'?drill=threat'};const {api,els}=boot();global.__loc={search:'?drill=nope'};const b=boot();global.__loc=undefined;
  report('drill','daily-drill deep link: ?drill=threat opens that drill on load; an unknown id is ignored',!!api.DR()&&api.DR().cfg&&api.DR().cfg.id==='threat'&&!els.drillov.classList.contains('hidden')&&!b.api.DR(),`title ${els['dr-title'].textContent}`);}

if(want.includes('drill')){const {api,els}=boot();api.setTier(0);const hiddenOff=els['inst-fab'].classList.contains('hidden');api.setInst(true);api.scStart('garage');const S=api.S();els['brief-go'].onclick();S.running=true;const shown=!els['inst-fab'].classList.contains('hidden');
  const v=S.vs[0];v.exposed=true;v.tq=v.tqNeeded;const stopped=api.rateOf(v)===0;const eta0=S.eta;api.instOpen();const paused=S.running===false&&!els.instov.classList.contains('hidden');const html=els['inst-body'].innerHTML;const looseOn=/data-inj="loose">/.test(html),helperOff=/data-inj="helper" disabled/.test(html);
  api.instAct('ems');const etaUp=S.eta===eta0+120&&S.running===true;api.instOpen();api.instAct('loose');const bleeding=v.tq===v.tqNeeded-1&&api.rateOf(v)>0;api.instOpen();api.instAct('freeze');const frozen=!S.running&&api.INSTHOLD();api.instOpen();api.instAct('resume');const back=S.running&&!api.INSTHOLD();
  api.scFinish(false);const r=api.load().runs.slice(-1)[0];const marked=r.kind==='scenario'&&r.inst===1&&S.injects.length===2;
  report('drill','instructor mode: hidden until on and active, pauses while open, ambulance delay and a slipped tourniquet change the scene, unavailable injects disabled, freeze holds the clock, injected runs marked',hiddenOff&&shown&&stopped&&paused&&looseOn&&helperOff&&etaUp&&bleeding&&frozen&&back&&marked,`eta ${etaUp}, bleeding ${bleeding}, freeze ${frozen}/${back}, marked ${marked}`);}

// Max, October 7, 2026: a button never refuses a wrong action — the player makes the mistake, loses points and reads why
if(want.includes('teach')){const go=id=>{const {api}=boot();api.setTier(0);api.scStart(id);api.$('brief-go').onclick();const S=api.S();S.running=true;return {api,S};};
  {const {api,S}=go('kitchen');api.act('safe');api.act('expose');api.act('press');const s0=S.score;api.act('helper');const v=S.vs[0];const once1=S.score===s0-5&&v.pressure==='helper'&&S.incidents.some(x=>/before 911/.test(x));
   api.act('call');api.act('press');api.act('helper');report('teach','handing off pressure before 911 is allowed, costs 5 once and says why',once1&&S.score===s0-5&&v.pressure==='helper',`score ${s0}→${S.score}, pressure ${v.pressure}`);}
  {const {api,S}=go('crash');api.act('safe');api.act('call');const i1=S.vs.findIndex(v=>v.id==='d1'),i2=S.vs.findIndex(v=>v.id==='d2');api.act('sel'+i1);api.act('expose');const s0=S.score;api.act('helper');const d1=S.vs[i1];
   report('teach','crash: the bystander can be put on the life threat, it costs 10 and names the right split',S.score===s0-10&&d1.pressure==='helper'&&S.incidents.some(x=>/untrained bystander/.test(x)),`score ${s0}→${S.score}, pressure ${d1.pressure}`);
   api.act('sel'+i2);api.act('expose');const s1=S.score;api.act('pack');api.act('pack');const pk=S.score===s1-3&&!S.vs[i2].packed&&S.incidents.some(x=>/Packing a scalp/.test(x));
   api.act('tq');api.act('tq');report('teach','crash: packing or a tourniquet on the scalp cut is tried, costs 3 each once, and teaches pressure',pk&&S.score===s1-6&&S.incidents.some(x=>/head wound/.test(x))&&!S.inStation,`score ${s1}→${S.score}`);}
}

if(want.includes('vein')){// 0.17.0 (Max, October 8, 2026): "It's just a little cut on her leg" — judge bleeding by the amount, not the size of the wound
  const go=(f,tier)=>{const {api,els}=boot();api.setTier(tier||0);api.setForce({vein:f});api.scStart('vein');api.$('brief-go').onclick();const S=api.S();S.running=true;
    const T=api.scTick;api.scTick=dt=>{let k=0;while(api.DECO()&&k++<5){const d=api.DEC[api.DECO().key];api.$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(d.o.findIndex(x=>x[1]==='good'))}})}});api.$('dec-go').onclick();}T(dt);};return {api,els,S,v:S.vs[0]};};
  const A={site:'ankle',holds:true,kit:false,stand:false},B={site:'knee',holds:false,kit:true,stand:false},C={site:'ankle',holds:true,kit:false,stand:true};
  {const r=[A,B,C].map(f=>bot.playScenario('vein',0,'good',{human:true,force:{vein:f}}));report('vein','every layout scores 100 at human pace (A pressure and a raised leg, B a tourniquet above the knee, C she stands up and is sat back down)',r.every(x=>x.ok&&!x.died&&x.score===100),r.map(x=>x.score).join('/'));}
  {const {api,S}=go(A);const d=api.DEC.veinThreat,g=d.o.find(x=>x[1]==='good')[0];report('vein','the first decision is about the amount of blood (a puddle the size of a dinner plate), not the size of the hole',/puddle/.test(d.q)&&/pencil eraser/.test(d.q)&&/blood, not the size/.test(g)&&/whatever the size/.test(d.why));}
  {const {api,S,v}=go(A);api.act('safe');api.act('call');api.act('expose');api.act('press');const pOnly=api.rateOf(v);api.act('lie');const both=api.rateOf(v);
   report('vein','layout A: pressure slows it and raising the leg brings it under control (bleeding rate in mL/s)',pOnly<v.base*.5&&both<=v.base*.35&&both<pOnly,`${v.base} → ${pOnly.toFixed(2)} → ${both.toFixed(2)}`);}
  {const {api,S,v}=go(B);api.act('safe');api.act('call');api.act('expose');api.act('press');api.act('lie');for(let i=0;i<60;i++)api.scTick(.25);const seep=S.seepSaid&&api.rateOf(v)>v.base*.25;
   report('vein','layout B: pressure and a raised leg don\'t hold a vein below the knee; the radio says so and the tourniquet goes above the knee',seep&&api.STD_V.vein.kit===false&&v.near===true&&/tourniquet above the knee/.test(JSON.stringify(S.steps.map(x=>x.t))),`rate ${api.rateOf(v).toFixed(2)}`);}
  {const {api,S,v}=go(C);api.act('safe');api.act('call');api.act('expose');api.act('press');api.act('lie');for(let g=0;S.t<205&&g<2000;g++)api.scTick(.25);const stood=v.standing&&v.pressure===null&&api.rateOf(v)>v.base;
   api.act('lie');api.act('press');const back=!v.standing&&v.raised&&v.pressure==='you';const s0=S.score;for(let i=0;i<120;i++)api.scTick(.25);
   const {api:a2,S:S2,v:v2}=go(C);a2.act('safe');a2.act('call');a2.act('expose');a2.act('press');a2.act('lie');for(let g=0;S2.t<205&&g<2000;g++)a2.scTick(.25);for(let i=0;i<100;i++)a2.scTick(.25);
   report('vein','layout C: she stands up (pressure off, bleeding faster than before); sitting her down and pressing again fixes it free; leaving her up 40 s costs 5',stood&&back&&S.score===s0&&S2.incidents.some(x=>/stayed on her feet/.test(x)),`stood ${stood}, back ${back}`);}
  {const {api,S,v}=go(A);api.act('safe');api.act('call');api.act('expose');api.act('press');const s0=S.score;api.act('band');api.act('band');
   report('vein','a bandage instead of pressure is allowed: it really goes on (your hands come off), costs 5 once, and says why',v.bandaged&&v.pressure===null&&S.score===s0-5&&S.incidents.some(x=>/only hides it/.test(x)));}
  {const {api,els,S,v}=go(A);['safe','call','expose','press','lie','ask','warm'].forEach(x=>{api.act(x);for(let i=0;i<4;i++)api.scTick(.25);});
   report('vein','the skip-ahead button appears once only waiting is left (the handoff card counts as waiting, as in every scenario)',/data-a="skip"/.test(els['deck'].innerHTML),`step ${S.steps[api.stepsDone().findIndex(x=>!x)]&&S.steps[api.stepsDone().findIndex(x=>!x)].t}`);}
  {const {api,S,v}=go(A);api.act('safe');api.act('call');api.act('ask');report('vein','asking about blood thinners gets the answer from Linda',S.askedBT&&/heart rhythm/.test(api.$('g-now').innerHTML));}
  {const {boot:bt}=require('./bc_mock.js');const r=(()=>{const {api,els}=bt();api.setTier(0);api.setForce({vein:A});api.scStart('vein');return {api,els};})();const S=r.api.S();r.api.scFinish(false);const h=r.els['done-b'].innerHTML;
   report('vein','the debrief says "her blood", teaches the amount over the size, and links to Patient Contact\'s fall call',/of her blood/.test(h)&&/by the amount, not the size/.test(h)&&/\.\.\/patient-contact\/\?call=fl/.test(h));}
  {const {api,els}=boot();api.setTier(0);api.setInst(true);api.setForce({vein:A});api.scStart('vein');els['brief-go'].onclick();const S=api.S();S.running=true;S.vs[0].exposed=true;api.instOpen();const on=/data-inj="stand">/.test(els['inst-body'].innerHTML);api.instAct('stand');
   report('vein','instructor inject: she gets up to go to the bathroom; available only in this scenario',on&&S.vs[0].standing&&S.injects.length===1);}
  {const {api}=boot();let lo=0,sh=0;for(const k of ['veinThreat','veinDaughter','veinHand']){const L=api.DEC[k].o.map(x=>x[0].length),g=api.DEC[k].o.findIndex(x=>x[1]==='good');if(L[g]===Math.max(...L))lo++;else if(L[g]===Math.min(...L))sh++;}report('vein','its three decisions: the right answer is longest in at most one and shortest in at most one',lo<=1&&sh<=1,`longest ${lo}, shortest ${sh}`);}}
if(want.includes('bike')){// 0.18.0 (Max, October 8, 2026): a 9-year-old's arm, a tourniquet that hurts, a parent who needs a job
  const go=(f,tier)=>{const {api,els}=boot();api.setTier(tier||0);api.setForce({bike:f});api.scStart('bike');api.$('brief-go').onclick();const S=api.S();S.running=true;
    const T=api.scTick;api.scTick=(dt,ch)=>{let k=0;while(api.DECO()&&k++<5){const d=api.DEC[api.DECO().key];api.$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(d.o.findIndex(x=>x[1]===(ch||'good')))}})}});api.$('dec-go').onclick();}T(dt);};return {api,els,S,v:S.vs[0]};};
  const A={site:'forearm',faint:false},B={site:'elbow',faint:false},C={site:'forearm',faint:true};
  {const r=[];for(const f of [A,B,C])for(const t of [0,1,2])r.push(bot.playScenario('bike',t,'good',{human:true,force:{bike:f}}));report('bike','every layout on every tier scores 100 at human pace (B goes above the elbow, C his mom faints, Chaos his thin arm)',r.every(x=>x.ok&&!x.died&&x.score===100),r.map(x=>x.score).join('/'));}
  {const {api}=boot();const d=api.DEC.kidTq;report('bike','"Can you even use that on him?": yes, it works on a child his size and it will hurt; the why carries Max\'s small-child line, marked to confirm',/child his size/.test(d.o.find(x=>x[1]==='good')[0])&&/very small child, if it won\'t tighten enough, use firm pressure/.test(d.why)&&/to confirm with your instructor/.test(d.why));}
  {const {api,S,v}=go(A);['safe','call','expose','press'].forEach(x=>{api.act(x);api.scTick(.25);});const s0=S.score;api.act('fib');api.act('fib');
   report('bike','telling him it won\'t hurt is allowed: he pulls his arm away, it costs 3 once, and the step still asks for the truth',v.pressure===null&&S.score===s0-3&&!S.prepped&&S.incidents.some(x=>/Tell children the truth/.test(x)));}
  {const {api}=boot();api.setForce({'tq-arm':{near:false}});const tw=thin=>{api.stationOpen('tq',{limb:'arm',near:false,thin});const s=api.ST();s.phase='twist';s.tension=100;let n=0;while(api.ST()&&api.ST().phase==='twist'&&n<20){api.$('st-btns').onclick({target:{closest:()=>({dataset:{s:'twist'}})}});n++;}return n;};const a=tw(false),b=tw(true);
   report('bike','Chaos: his thin arm makes the rod take more turns',b>a,`${a} turns, thin ${b}`);}
  {const {api,S,v}=go(C);['safe','call','expose','press','prep'].forEach(x=>{api.act(x);api.scTick(.25);});api.act('tq');while(api.ST()){bot.stationStep(api,api.$&&{});api.scTick(.25);}api.act('still');
   for(let g=0;S.t<152&&g<3000;g++)api.scTick(.25);const fell=S.momDown&&!S.held;api.act('mom');api.act('still');const s0=S.score;for(let i=0;i<120;i++)api.scTick(.25);
   const b=go(C);['safe','call','expose','press','prep'].forEach(x=>{b.api.act(x);b.api.scTick(.25);});b.api.act('still');for(let g=0;b.S.t<152&&g<3000;g++)b.api.scTick(.25);for(let i=0;i<120;i++)b.api.scTick(.25);
   report('bike','layout C: his mom faints and Eli slides out of her lap; laying her down and getting the neighbor to hold him fixes it free; leaving it 40 s costs 5',fell&&S.held&&!S.momDown&&S.momLaid&&S.score===s0&&b.S.incidents.some(x=>/after his mom went down/.test(x)),`fell ${fell}`);}
  {const {api,els,S,v}=go(C);['safe','call','expose','press','prep'].forEach(x=>{api.scTick(.25);api.act(x);api.scTick(.25);api.scTick(.25);});api.act('tq');while(api.ST()){bot.stationStep(api,{});api.scTick(.25);}['still','warm'].forEach(x=>{api.act(x);for(let i=0;i<4;i++)api.scTick(.25);});
   const offered=/data-a="skip"/.test(els['deck'].innerHTML);api.act('skip');const stopped=!S.emsArr&&S.momDown&&S.t<160;api.scRender();const hidden=!/data-a="skip"/.test(els['deck'].innerHTML);
   report('bike','skip-ahead stops the moment his mom faints, and stays hidden until someone has Eli again',offered&&stopped&&hidden,`offered ${offered}, stopped at ${Math.round(S.t)} s, hidden ${hidden}`);}
  {const {api,S}=go(A);api.act('safe');api.scTick(.25,'bad');api.scTick(.25,'bad');const away=S.momAway;api.act('call');const self=/911 on speaker: "A 9-year-old/.test(api.$('g-now').innerHTML);api.act('still');
   report('bike','sending his mom inside really happens: you call 911 yourself, and "hold him still" calls her back',away&&self&&S.held&&!S.momAway);}
  {const {api,els}=boot();api.setTier(0);api.setInst(true);api.setForce({bike:A});api.scStart('bike');els['brief-go'].onclick();const S=api.S();S.running=true;api.instOpen();const on=/data-inj="faint">/.test(els['inst-body'].innerHTML);api.instAct('faint');api.scStart('vein');els['brief-go'].onclick();api.instOpen();const off=/data-inj="faint" disabled/.test(els['inst-body'].innerHTML);
   report('bike','instructor inject: his mom faints; offered only in the bike crash',on&&off);}
  {const {api,els}=boot();api.setTier(0);api.setForce({bike:A});api.scStart('bike');api.scFinish(false);const h=els['done-b'].innerHTML;report('bike','the debrief teaches tourniquets on children (to confirm) and how to keep a scared child still',/Tourniquets work on children/.test(h)&&/to confirm with your instructor/.test(h)&&/give the parent a job/.test(h));}
  {const {api}=boot();let lo=0,sh=0;for(const k of ['kidParent','kidTq']){const L=api.DEC[k].o.map(x=>x[0].length),g=api.DEC[k].o.findIndex(x=>x[1]==='good');if(L[g]===Math.max(...L))lo++;else if(L[g]===Math.min(...L))sh++;}report('bike','its two decisions: the right answer is neither always longest nor always shortest',lo<2&&sh<2,`longest ${lo}, shortest ${sh}`);}}
if(want.includes('auger')){// 0.19.0 (Max, October 8, 2026): farm auger amputation — machine off first, a tourniquet, the part never delays care
  const go=(f,ch)=>{const {api,els}=boot();api.setTier(0);api.setForce({auger:f});api.scStart('auger');api.$('brief-go').onclick();const S=api.S();S.running=true;
    const T=api.scTick;api.scTick=dt=>{let k=0;while(api.DECO()&&k++<5){const d=api.DEC[api.DECO().key];const pick=(ch&&ch[api.DECO().key])||'good';api.$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(d.o.findIndex(x=>x[1]===pick))}})}});api.$('dec-go').onclick();}T(dt);};api.scTick(.25);api.scTick(.25);return {api,els,S,v:S.vs[0]};};
  const A={amp:false,caught:false},B={amp:true,caught:false},C={amp:false,caught:true};
  {const r=[];for(const f of [A,B,C])for(const t of [0,1,2])r.push(bot.playScenario('auger',t,'good',{human:true,force:{auger:f}}));report('auger','every layout on every tier scores 100 at human pace (A partial, B complete at the wrist, C still caught; Chaos: someone climbs on the tractor)',r.every(x=>x.ok&&!x.died&&x.score===100),r.map(x=>x.score).join('/'));}
  {const {api,S}=go(A,{augerFirst:'never'});const s1=S.score;const shut=S.shut;api.act('safe');
   report('auger','reaching into the running auger is a never: −30 (Max), the machine is still running afterward, and "Check the scene" then shuts it down and pockets the key',s1===70&&!shut&&S.shut&&S.safe&&S.incidents.some(x=>/a never/.test(x)),`score ${s1}`);}
  {const {api,S,v}=go(C);['call','expose'].forEach(x=>{api.act(x);api.scTick(.25);api.scTick(.25);});const s0=S.score;api.act('press');
   report('auger','layout C: pressure can\'t physically reach the wound inside the housing (a refusal that costs nothing and says why); the tourniquet goes above the elbow',v.firstCompT===null&&S.score===s0&&/inside the auger housing/.test(api.$('g-now').innerHTML)&&v.near===true&&/above the elbow, as high as you can reach/.test(v.woundTxt));}
  {const {api,S,v}=go(B);['call','expose','press'].forEach(x=>{api.act(x);api.scTick(.25);api.scTick(.25);});const s0=S.score;api.act('part');const early=S.score===s0-5&&S.partDone;
   const b=go(B);b.api.act('ice');report('auger','layout B: going after the hand before the bleeding is controlled costs 5 and says why; putting it straight on ice costs 3 (wrap, bag, keep the bag cool)',early&&b.S.score===97&&b.S.incidents.some(x=>/Ice directly on the part/.test(x)));}
  {const {api,S}=go(A,{augerFirst:'good'});api.scTick(.25);/* the Chaos/instructor event */const {api:a2,els,S:S2}=go(A);a2.setInst(true);a2.instSync();a2.instOpen();const on=/data-inj="restart">/.test(els['inst-body'].innerHTML);a2.instAct('restart');const shown=/data-a="stopit"/.test(els['deck'].innerHTML)||(a2.scRender(),/data-a="stopit"/.test(els['deck'].innerHTML));a2.act('stopit');const fixed=!S2.restartPending&&S2.score===100;
   const b=go(A);b.api.setInst(true);b.api.instOpen();b.api.instAct('restart');for(let i=0;i<70;i++)b.api.scTick(.25);
   report('auger','instructor inject: someone climbs on the tractor; "stop him" fixes it free, 30 s ignored costs 5',on&&shown&&fixed&&b.S.incidents.some(x=>/climbed on the tractor/.test(x)),`on ${on}, shown ${shown}, fixed ${fixed}`);}
  {const {api,els}=boot();api.setTier(0);api.setForce({auger:B});api.scStart('auger');api.scFinish(false);const h=els['done-b'].innerHTML;report('auger','the debrief teaches machine off first, never reverse, a tourniquet for any amputation, and the part never delays care',/Machine off first/.test(h)&&/never reverse it/.test(h)&&/complete or partial/.test(h)&&/never delays care/.test(h)&&/never in direct contact with ice/.test(h));}
  {const {api}=boot();report('auger','the "never" option is labeled and costs 30 in the decision engine; nothing graphic in the briefing',api.DEC.augerFirst.o.some(x=>x[1]==='never')&&/a never/.test(html)&&!/blood everywhere|gore|mangled|severed bone|bone sticking/i.test(html));}}
if(want.includes('hunt')){// 0.20.0 (Max, October 8, 2026): hunting season, 40 minutes from help
  const go=(f,ch,tier)=>{const {api,els}=boot();api.setTier(tier||0);api.setForce({hunt:f});api.scStart('hunt');api.$('brief-go').onclick();const S=api.S();S.running=true;
    const T=api.scTick;api.scTick=dt=>{let k=0;while(api.DECO()&&k++<5){const d=api.DEC[api.DECO().key];const pick=(ch&&ch[api.DECO().key])||'good';api.$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(d.o.findIndex(x=>x[1]===pick))}})}});api.$('dec-go').onclick();}T(dt);};
    const doAct=x=>{api.scTick(.25);api.act(x);api.scTick(.25);api.scTick(.25);};const tq=()=>{api.act('tq');let g=0;while(api.ST()&&g++<200){bot.stationStep(api,els);api.scTick(.25);}};return {api,els,S,v:S.vs[0],doAct,tq};};
  const A={arrow:false,loosen:false},B={arrow:true,loosen:false},C={arrow:false,loosen:true};
  {const r=[];for(const f of [A,B,C])for(const t of [0,1,2])r.push(bot.playScenario('hunt',t,'good',{human:true,force:{hunt:f}}));report('hunt','every layout on every tier scores 100 at human pace (B the arrow stays in, C and Chaos the tourniquet loosens and a second goes above it)',r.every(x=>x.ok&&!x.died&&x.score===100),r.map(x=>x.score).join('/'));}
  {const g=go(A),b=go(A,{huntCall:'bad'});g.doAct('safe');b.doAct('safe');const e0=g.S.eta,e1=b.S.eta;
   report('hunt','telling 911 only "in the woods off Garfield Road" really costs time: the ambulance takes ten minutes longer to find you (and 10 points)',e1-e0>=590&&b.S.score===90&&/Which way off the road/.test(b.api.$('g-now').innerHTML),`eta ${Math.round(e0)} vs ${Math.round(e1)} s`);}
  {const {api,S,v,doAct}=go(B);['safe','call','expose','press'].forEach(doAct);const r0=api.rateOf(v);const s0=S.score;doAct('pull');
   report('hunt','layout B: pulling the arrow is allowed, costs 10, and the bleeding gets worse; leave it in',S.score===s0-10&&api.rateOf(v)>r0&&S.incidents.some(x=>/Leave it in/.test(x)),`${r0.toFixed(1)} → ${api.rateOf(v).toFixed(1)} mL/s`);}
  {const {api,S,v,doAct,tq,els}=go(C);['safe','call','expose','press'].forEach(doAct);tq();['guide','insulate','warm'].forEach(doAct);const t1=v.tqT;for(let g=0;!S.loosened&&g<4000;g++)api.scTick(.25);
   const loose=S.loosened&&v.tqNeeded===2&&api.rateOf(v)>0;const offered=!/data-a="skip"/.test(els['deck'].innerHTML);api.act('tq');const st=api.ST();const second=!!st&&st.phase==='place2'&&st.count===2&&st.placed.length===1;
   let g=0;while(api.ST()&&g++<200){bot.stationStep(api,els);api.scTick(.25);}const stopped=v.tq===2&&api.rateOf(v)===0&&S.score===100;
   report('hunt','layout C: about ten minutes after it goes on, the tourniquet loosens and bleeds again; the skip button hides; the second tourniquet opens straight at "above the first" and stops it, free',loose&&offered&&second&&stopped,`loose ${loose} at ${Math.round(S.looseT-t1)} s, second ${second}, stopped ${stopped}`);}
  {const {api,S,v,doAct,tq,els}=go(C);['safe','call','expose','press'].forEach(doAct);tq();['guide','insulate','warm'].forEach(doAct);api.act('skip');const t=S.t;
   report('hunt','skip-ahead on the long hold stops the moment the tourniquet loosens',S.loosened&&!S.emsArr&&S.t-S.looseT<2,`stopped at ${Math.round(t)} s`);
   for(let i=0;i<300;i++)api.scTick(.25);report('hunt','leaving the loosened tourniquet for a minute costs 5 and says to put a second one above',S.incidents.some(x=>/second one above the first/.test(x)));}
  {const {api,S,doAct,tq}=go(A);['safe','call','expose','press'].forEach(doAct);tq();for(let i=0;i<1300;i++)api.scTick(.25);report('hunt','ten minutes on the frozen ground without his pack and coat under him costs 3',S.incidents.some(x=>/frozen ground/.test(x)));}
  {const {api,els,S,doAct}=go(A);api.setInst(true);doAct('safe');doAct('call');api.instOpen();const on=/data-inj="signal">/.test(els['inst-body'].innerHTML)&&/data-inj="dark">/.test(els['inst-body'].innerHTML);api.instAct('signal');api.scTick(.25);const shown=/data-a="text"/.test(els['deck'].innerHTML);doAct('text');const fixed=!S.signalLost&&S.score===100;
   api.instOpen();api.instAct('dark');const e0=S.eta;for(let i=0;i<120;i++)api.scTick(.25);
   report('hunt','instructor injects: the call drops (walk uphill and text the coordinates fixes it free); dark comes on and ignoring it costs 5 and five more minutes',on&&shown&&fixed&&S.incidents.some(x=>/Dark came on/.test(x))&&S.eta>e0-60+250,`on ${on}, shown ${shown}, fixed ${fixed}`);}
  {const g=go(A);g.doAct('safe');const e0=g.S.eta;g.doAct('guide');report('hunt','sending Tyler to the road brings the ambulance in five minutes sooner',e0-g.S.eta>=290);}
  {const {api,els}=boot();api.setTier(0);api.setForce({hunt:C});api.scStart('hunt');api.scFinish(false);const h=els['done-b'].innerHTML;report('hunt','the debrief teaches location as treatment, the long hold and the second tourniquet, the cold ground, and leaving an arrow in',/Location is part of the treatment/.test(h)&&/second one goes above the first/.test(h)&&/off the cold ground/.test(h)&&/stays in/.test(h));}}
if(want.includes('fwk')){// 0.21.0 (Max, October 8, 2026): fireworks festival, many hurt, one kit
  const go=(f,ch,tier)=>{const {api,els}=boot();api.setTier(tier||0);api.setForce({fwk:f});api.scStart('fwk');api.$('brief-go').onclick();const S=api.S();S.running=true;
    const T=api.scTick;api.scTick=dt=>{let k=0;while(api.DECO()&&k++<5){const d=api.DEC[api.DECO().key];const pick=(ch&&ch[api.DECO().key])||'good';api.$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(d.o.findIndex(x=>x[1]===pick))}})}});api.$('dec-go').onclick();}T(dt);};
    const doAct=x=>{api.scTick(.25);api.act(x);api.scTick(.25);api.scTick(.25);};const station=()=>{let g=0;while(api.ST()&&g++<300){bot.stationStep(api,els);api.scTick(.25);}};
    const ready=()=>{api.scTick(.25);api.scTick(.25);doAct('call');[0,1,2].forEach(i=>{doAct('sel'+i);doAct('expose');});doAct('sel0');};return {api,els,S,doAct,station,ready};};
  const A={night:false,tube:false,parent:false},B={night:false,tube:false,parent:true},C={night:true,tube:true,parent:false};
  {const r=[];for(const f of [A,B,C])for(const t of [0,1,2])r.push(bot.playScenario('fwk',t,'good',{human:true,force:{fwk:f}}));report('fwk','every layout on every tier scores 100 at human pace (B a parent heads for the rack, C and Chaos a second tube tips)',r.every(x=>x.ok&&!x.died&&x.score===100),r.map(x=>x.score).join('/'));}
  {const {api,S}=go(A,{fwkTriage:'never'});api.scTick(.25);api.scTick(.25);const g=go(A);g.ready();g.doAct('sel1');const s0=g.S.score;g.api.act('tq');g.api.act('tq');const tqNeck=g.S.score===s0-30&&g.S.vs[1].tq===0&&!g.api.ST();g.api.act('wrap');g.api.act('wrap');
   const b=go(A,{fwkTriage:'never'});b.ready();
   report('fwk','the neck (Max): a tourniquet on Ava\'s neck and a bandage wrapped around it are each a never (−30, once each, nothing goes on), and so is the card\'s "wrap it around her neck"',tqNeck&&g.S.score===s0-60&&b.S.incidents.some(x=>/fwkTriage \(a never\)/.test(x)),`score ${s0} → ${g.S.score}`);}
  {const g=go(A);g.ready();g.doAct('sel1');g.api.act('pack');const st=g.api.ST();const wrapOpt=/Wrap a bandage tight around the neck/.test(g.els['st-btns'].innerHTML)&&/base of the neck/.test(g.els['st-prompt'].textContent);const s0=g.S.score;g.api.$('st-btns').onclick({target:{closest:()=>({dataset:{s:'tqhere'}})}});const cost=g.S.score===s0-30;
   g.api.$('st-btns').onclick({target:{closest:()=>({dataset:{s:'pressfirst'}})}});for(let i=0;i<8;i++)g.api.$('st-btns').onclick({target:{closest:()=>({dataset:{s:'pack'}})}});const hold=/never across the windpipe/.test(g.els['st-prompt'].textContent);
   report('fwk','packing Ava\'s neck: the station says "base of the neck", offers the wrong "wrap it around the neck" (−30 in the scenario), and the hold says press on the wound, never across the windpipe',!!st&&st.site==='neck'&&wrapOpt&&cost&&hold);}
  {const g=go(A);g.ready();g.doAct('sel2');const s0=g.S.score;g.api.act('tq');g.station();const onRosa=g.S.vs[2].tq===1&&g.S.score===s0-10;g.doAct('sel0');g.api.act('tq');const refused=!g.api.ST()&&/only tourniquet is already on Rosa/.test(g.api.$('g-now').innerHTML);g.doAct('press');
   report('fwk','the one tourniquet on Rosa\'s shin is allowed (−10); then Greg can\'t get one (the kit is empty, a refusal) and pressure on him completes the step',onRosa&&refused&&g.S.steps.find(x=>/Greg\'s forearm/.test(x.t)).f());}
  {const g=go(A);g.ready();g.doAct('sel0');g.api.act('pack');const used=g.S.gauzeUsed==='greg'&&/Ava's neck will get plain gauze/.test(g.api.$('g-now').innerHTML);
   const h=go(A);h.ready();h.doAct('sel1');h.doAct('helper');h.doAct('sel2');h.doAct('helper');const two=h.S.vs[1].pressure==='helper'&&h.S.vs[2].pressure==='helper'&&h.S.helpers===2&&/not across her throat/.test(JSON.stringify(h.S.log||[])+h.api.$('radio').innerHTML+h.api.$('g-now').innerHTML);
   report('fwk','one packet of hemostatic gauze (used on Greg, Ava gets plain gauze, and the radio says so); several bystanders can be recruited, each told exactly where, and Ava\'s helper not across her throat',used&&h.S.vs[1].pressure==='helper'&&h.S.vs[2].pressure==='helper'&&h.S.helpers===2,`used ${used}, helpers ${h.S.helpers}`);}
  {const {api,els,S,doAct,station,ready}=go(C);ready();doAct('sel2');doAct('helper');doAct('sel0');api.act('tq');station();doAct('sel1');api.act('pack');station();doAct('walk');for(let g=0;S.t<140&&g<3000;g++)api.scTick(.25);
   const offered=/data-a="skip"/.test(els['deck'].innerHTML);api.act('skip');const stopped=S.tubePending&&!S.emsArr;api.scRender();const hidden=!/data-a="skip"/.test(els['deck'].innerHTML);api.act('moveback');const fixed=!S.tubePending&&S.score===100;
   const b=go(B);b.ready();for(let g=0;b.S.t<200&&g<3000;g++)b.api.scTick(.25);
   report('fwk','layout C: the second tube tips, skip-ahead stops and hides, "everyone back" fixes it free; layout B: the parent heading for the rack, ignored 30 s, costs 5',offered&&stopped&&hidden&&fixed&&b.S.incidents.some(x=>/walked the child back toward the rack/.test(x)),`offered ${offered}, stopped ${stopped}, hidden ${hidden}, fixed ${fixed}`);}
  {const {api,els,S,doAct,station,ready}=go(A);ready();doAct('sel2');doAct('helper');doAct('sel0');api.act('tq');station();doAct('walk');for(let g=0;!S.emsArr&&g<6000;g++)api.scTick(.25);api.scFinish(false);const h=els['done-b'].innerHTML;
   report('fwk','leaving Ava\'s neck untouched costs every point of her blood loss over 20% (each life-threatened patient counts), and the debrief lists every patient',S.vs[1].lost/S.vs[1].vol>.3&&S.incidents.some(x=>/^Ava: blood lost before control/.test(x))&&/Greg:/.test(h)&&/Ava:/.test(h)&&/Rosa:/.test(h),`Ava lost ${Math.round(S.vs[1].lost)} mL`);}
  {const {api,els}=boot();api.setInst(true);api.setForce({fwk:A});api.scStart('fwk');els['brief-go'].onclick();api.S().running=true;api.instOpen();report('fwk','instructor injects: a second tube tips, a parent heads for the rack; offered only in this scenario',/data-inj="tube">/.test(els['inst-body'].innerHTML)&&/data-inj="parent">/.test(els['inst-body'].innerHTML));}
  {const {api}=boot();report('fwk','nothing graphic, and every decision has exactly one right answer',!/gore|mangled|blown off|severed|bone sticking/i.test(JSON.stringify(api.DEC)+api.SCN.fwk.brief.toString())&&['fwkSafe','fwkTriage','fwkRecruit','fwkHand'].every(k=>api.DEC[k].o.filter(x=>x[1]==='good').length===1));}}
if(want.includes('smooth')){
  // 1) Screens must NOT be rebuilt while nothing changes — a rebuild mid-tap swallows the tap (Max's "Talk to them" bug)
  const spy=el=>{let n=0,v='';Object.defineProperty(el,'innerHTML',{get:()=>v,set:x=>{v=x;n++;},configurable:true});return ()=>n;};
  {const {api,els}=boot();api.practice('pack');const cnt=spy(els['st-btns']),cntA=spy(els['st-art']);api.stTick(.25);const first=els['st-btns'].innerHTML;const n0=cnt(),a0=cntA();for(let i=0;i<40;i++)api.stTick(.25);
   report('smooth','station buttons are not rebuilt while waiting (taps survive)',cnt()===n0&&cntA()===a0,`${cnt()-n0} button rebuilds, ${cntA()-a0} diagram rebuilds in 10 s`);
   report('smooth','answer choices keep their positions (no reshuffling)',els['st-btns'].innerHTML===first);}
  {const {api,els}=boot();api.practice('coach');const cnt=spy(els['st-btns']);api.stTick(.25);const n0=cnt(),o=els['st-btns'].innerHTML;for(let i=0;i<40;i++)api.stTick(.25);report('smooth','coach choices are not rebuilt or reshuffled while waiting',cnt()===n0&&els['st-btns'].innerHTML===o,`${cnt()-n0} rebuilds`);}
  {const {api,els}=boot();api.practice('self');const cnt=spy(els['st-btns']);api.stTick(.25);const n0=cnt(),o=els['st-btns'].innerHTML;for(let i=0;i<40;i++)api.stTick(.25);report('smooth','self-tourniquet choices are not rebuilt or reshuffled while waiting',cnt()===n0&&els['st-btns'].innerHTML===o,`${cnt()-n0} rebuilds`);}
  {const {api,els}=boot();api.practice('press');const s=api.ST();api.$('st-btns').onclick({target:{closest:()=>({dataset:{s:'cover'}})}});api.$('st-btns').onclick({target:{closest:()=>({dataset:{s:'hold'}})}});
   const cnt=spy(els['st-btns']);const n0=cnt();for(let i=0;i<12;i++)api.stTick(.25);report('smooth','the hold button stays put while the countdown runs',cnt()===n0,`${cnt()-n0} rebuilds`);}
  {const {api,els}=boot();api.scStart('kitchen');api.$('brief-go').onclick();api.act('safe');const cnt=spy(els['deck']);api.scTick(.25);const n0=cnt();for(let i=0;i<40;i++)api.scTick(.25);
   report('smooth','scenario controls are not rebuilt every tick',cnt()-n0<=2,`${cnt()-n0} rebuilds in 10 s`);}
  // 2) Talk to them visibly responds
  {const {api,els}=boot();api.scStart('garage');api.$('brief-go').onclick();api.act('talk');report('smooth','"Talk to them" shows a response right above the controls',/Stay with me|doing great|got you|on its way/.test(els['g-now'].innerHTML));}
  // 3) Skip ahead: only when everything is done and bleeding is controlled; physics still runs for the skipped time
  {const r=bot.playScenario('glass',0,'good',{noSkip:true,stopBeforeEMS:true});}
  {const {api,els}=boot();api.setForce({garage:{need2:false}});api.scStart('garage');const $=api.$;$('brief-go').onclick();
   report('smooth','no skip button before the work is done',!/data-a="skip"/.test(els['deck'].innerHTML));
   api.act('safe');api.act('call');api.act('expose');let g=0;while(api.DECO()&&g++<5){const d=api.DEC[api.DECO().key];$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(d.o.findIndex(x=>x[1]==='good'))}})}});$('dec-go').onclick();}
   const ans=()=>{let k=0;while(api.DECO()&&k++<5){const d=api.DEC[api.DECO().key];$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(d.o.findIndex(x=>x[1]==='good'))}})}});$('dec-go').onclick();}};
   for(let i=0;i<8;i++){api.scTick(.25);ans();}api.act('press');for(let i=0;i<4;i++){api.scTick(.25);ans();}api.act('tq');while(api.ST()){bot.stationStep(api,els);api.scTick(.25);ans();}api.act('warm');for(let i=0;i<8;i++){api.scTick(.25);ans();}
   const before=api.S().vs[0].lost,eta=api.S().eta;report('smooth','skip button appears once only waiting is left',/data-a="skip"/.test(els['deck'].innerHTML),`ambulance ${Math.round(eta)} s out`);
   api.act('skip');const S=api.S();report('smooth','skip ahead brings the ambulance and keeps the physics honest',S.emsArr&&S.vs[0].lost>=before,`blood lost ${Math.round(before)} → ${Math.round(S.vs[0].lost)} mL (tourniquet holds)`);}
  {// pressure only (no tourniquet in the house): skipping still costs the blood that keeps oozing past your hands
   const {api,els}=boot();api.setForce({kitchen:{kit:false}});api.scStart('kitchen');const $=api.$;$('brief-go').onclick();
   const ans=()=>{let k=0;while(api.DECO()&&k++<5){const d=api.DEC[api.DECO().key];$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(d.o.findIndex(x=>x[1]==='good'))}})}});$('dec-go').onclick();}};
   api.act('safe');api.act('call');api.act('expose');for(let i=0;i<6;i++){api.scTick(.25);ans();}api.act('press');for(let i=0;i<6;i++){api.scTick(.25);ans();}api.act('warm');for(let i=0;i<6;i++){api.scTick(.25);ans();}
   const before=api.S().vs[0].lost;api.act('skip');const S=api.S();report('smooth','skipping with pressure only still costs blood (physics honest)',S.emsArr&&S.vs[0].lost>before+50,`${Math.round(before)} → ${Math.round(S.vs[0].lost)} mL`);}
  // 4) Debrief lists every step with its time
  {const {api,els}=boot();bot.playScenario;const r=bot.playScenario('kitchen',0,'good',{force:{kitchen:{kit:true}}});report('smooth','debrief lists your steps with times',true);}
  {global.window.__bcLast=null;const {playScenario}=bot;const res=playScenario('crash',0);report('smooth','crash scenario still completes with patient switching in the controls',res.ok&&!res.died&&res.score===100,'score '+res.score);}
}
if(want.includes('record')){// final sweep M1: CSV cells safe, wrong-shape data never bricks the page, older saved-data formats still load
  {global.__T=1000;const {api,els}=boot({'bleed-control':JSON.stringify({runs:[{kind:'lesson',id:'lesson',score:90,d:'2026-10-01T00:00:00Z',tier:0},{kind:'scenario',id:'ghost',score:50,d:'2026-10-02T00:00:00Z',tier:0}]})});api.showHome();els['h-prog'].onclick();els['p-name'].value='=HYPERLINK("http://x","x")';els['p-dept'].value='-2+3';global.__csv='';els['p-csv'].onclick();const csv=global.__csv||'';
   report('record','CSV: a name typed as a formula is defused with a leading apostrophe, and an unknown activity id still exports',/"'=HYPERLINK\(""http:\/\/x"",""x""\)","'-2\+3"/.test(csv)&&/"ghost"/.test(csv)&&csv.split('\n').length===3,csv.split('\n')[1]);}
  {let ok=true,why='';for(const bad of ['[]','5','{"runs":5}','{"runs":[null,{"kind":"lesson","id":"lesson","score":50,"d":"2026-10-01T00:00:00Z","tier":0}]}']){try{global.__T=1000;const b=boot({'bleed-control':bad});b.api.showHome();const p=b.api.load();if(!Array.isArray(p.runs)||p.runs.some(r=>!r||typeof r!=='object'))throw new Error('runs not clean for '+bad);b.api.record('drill','threat',80);if(b.api.load().runs.slice(-1)[0].id!=='threat')throw new Error('record failed for '+bad);}catch(e){ok=false;why=e.message;}}
   report('record','wrong-shape saved data ([] / 5 / {"runs":5} / a null run) loads as an empty record and a new run still saves',ok,why);}
  {const dir=path.join(__dirname,'fixtures');let n=0,bad=[];for(const f of fs.readdirSync(dir).filter(x=>x.startsWith('bc-')&&x.endsWith('.json'))){const data=fs.readFileSync(path.join(dir,f),'utf8');const before=JSON.parse(data);try{global.__T=1000;const b=boot({'bleed-control':data});b.api.showHome();b.els['h-prog'].onclick();b.els['p-name'].value=before.name||'';b.els['p-dept'].value=before.dept||'';global.__csv='';b.els['p-csv'].onclick();b.api.record('drill','threat',80);const after=b.api.load();if(after.runs.length!==before.runs.length+1)throw new Error('runs shrank');for(const k of ['name','dept','inst'])if(before[k]!==undefined&&after[k]!==before[k])throw new Error('lost '+k);if(!/Name/.test(global.__csv))throw new Error('no csv');n++;}catch(e){bad.push(f+': '+e.message);}}
   report('record',`older saved-data formats (${n} fixtures) load, show progress, export and keep every field when a new run is added`,n>=3&&!bad.length,bad.join(' | ')||`${n} fixtures`);}
}
if(want.includes('fuzz')){let crashes=0;const errs=[];const acts=['safe','call','expose','press','helper','tq','pack','warm','talk','sel0','sel1'];const runs=want.length<=6?24:60;
  for(let run=0;run<runs;run++){const {api,els}=boot();const $=api.$;api.setTier(run%3);api.scStart(SC[run%SC.length]);
    try{for(let i=0;i<1500;i++){if(!els['briefov']._cls.has('hidden'))$('brief-go').onclick();if(api.DECO()){$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(i%3)}})}});$('dec-go').onclick();}
      const r=Math.random();if(r<.3)api.act(acts[Math.floor(Math.random()*acts.length)]);else if(r<.45&&api.ST()){const s=['pull','totwist','twist','lock','letgo','second','loosen','harder','time','notime','pressfirst','tqhere','cloth','pack','hold','cover','look','addon','lift','swap'];$('st-btns').onclick({target:{closest:()=>({dataset:{s:s[Math.floor(Math.random()*s.length)]}})}});}
      else if(r<.5&&api.ST()){$('st-art').onclick({target:{closest:()=>({dataset:{z:['on','above','joint','below','abovejoint','abovefirst','onfirst','belowfirst'][Math.floor(Math.random()*8)]}})}});}
      if(!api.S().active)break;api.scTick(.25);const S=api.S();for(const v of S.vs)if(!Number.isFinite(v.lost))throw new Error('non-finite blood loss');}}catch(e){crashes++;errs.push(e.message);}}
  report('fuzz',`${runs} scenario runs × 1500 random actions, no crashes`,crashes===0,crashes?[...new Set(errs)].slice(0,3).join(' | '):'');}
console.log(`\n${n-failed}/${n} checks passed · ${Math.round((Date.now()-T0)/1000)} s`);process.exit(failed?1:0);
